# Module manifest for module 'DrawIO'
# Generated by: David Stein
# Generated on: 4/15/2026

@{
RootModule = 'DrawIO.psm1'
ModuleVersion = '1.0.0'
# CompatiblePSEditions = @()
GUID = '3e148c5f-5a32-42d9-88a2-6ef0134fc0b3'
Author = 'David Stein'
CompanyName = 'Unknown'
Copyright = '(c) 2026 David Stein. All rights reserved.'
Description = 'A PowerShell module for integrating with Draw.IO.'
# PowerShellVersion = ''
# PowerShellHostName = ''
# PowerShellHostVersion = ''
# DotNetFrameworkVersion = ''
# ClrVersion = ''
# ProcessorArchitecture = ''
# RequiredModules = @()
# RequiredAssemblies = @()
# ScriptsToProcess = @()
# TypesToProcess = @()
# FormatsToProcess = @()
# NestedModules = @()
FunctionsToExport = @('New-DrawIODiagram','Add-DrawIOShape','Add-DrawIOEdge','Add-DrawIOSwimLane','Add-DrawIOGroup','Add-DrawIOPage','Set-DrawIODiagramProperty','Save-DrawIODiagram')
CmdletsToExport = '*'
VariablesToExport = '*'
AliasesToExport = '*'
# DscResourcesToExport = @()
# ModuleList = @()
# FileList = @()
PrivateData = @{
    PSData = @{
        Tags = @('Draw.IO', 'Diagramming', 'PowerShell', 'Draw', 'skatterbrainz')
        LicenseUri = 'https://github.com/Skatterbrainz/DrawIO/blob/main/LICENSE'
        ProjectUri = 'https://github.com/Skatterbrainz/DrawIO/'
        # IconUri = ''
        # ReleaseNotes = ''
        # Prerelease = ''
        # RequireLicenseAcceptance = $false
        # ExternalModuleDependencies = @()
    } # End of PSData hashtable
} # End of PrivateData hashtable
# HelpInfoURI = ''
# DefaultCommandPrefix = ''
}
